### ISSUE TITLE
Enhancement: allow shifted blocks to displace liquids

### ISSUE THREAD

**Issue by Katorone** [LolHens/mc-blockshifter#1]
I tried using shifting blocks to harvest a kelp farm, but discovered that water and flowing water stop blocks from being shifted.  Would it be possible to have shifted blocks behave more like an extended piston?  This way it can displace liquids and break certain crops/blocks, and a whole new array of vanilla+ farms become possible.

**Comment by LolHens** [comment]
Will look into that.

**Comment by LolHens** [comment]
fixed in v1.0.3

**Comment by Katorone** [comment]
Thank you!
