### ISSUE TITLE
Crash since forge 1.16.2-33.0.30

### ISSUE THREAD

**Issue by MeijinViper** [LolHens/mc-blockshifter#15]
Hi.  So, I've been trying to get this mod installed on my server.  Server details are:

MC 1.16.2
Forge 1.16.2 ver 33.0.31
Mods list is attached [pic]
![Capture](https://user-images.githubusercontent.com/70599799/91888914-a0f36300-ec52-11ea-8b58-2e80afc619a3.PNG)

So, when I put the mod in the mods folder in the server and restart the server, it refuses to start.  It starts and is stable with the other mods.  I dont have the error log since it is not loading on the server itself [havent tried client side yet].

**Comment by LolHens** [comment]
Did you also install the required dependency https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force?

**Comment by MeijinViper** [comment]
I did. It made no difference.  I even updated the server to Forge 33.0.32,
still wont start up with the mod installed.  I'm on Serverminer.
~Rob

**Comment by LolHens** [comment]
Okay thank you I could confirm the issue. Seems to be an issue with "Scalable Cats Force"

**Comment by LolHens** [comment]
https://github.com/Kotori316/SLP/issues/7

**Comment by MeijinViper** [comment]
I tried the older versions of Forge and still had the same issue.

**Comment by LolHens** [comment]
That's weird. You could try one last thing and update to the latest version of forge and ScalableCatsForce-2.13.3-build-3.
That combination worked for me on both client and server. If that doesn't work there might be another issue on your system. Maybe it will then at least create a logfile.

**Comment by MeijinViper** [comment]
VICTORY!!!!

Updated to Forge 33.0.34 (.35 crashed the server without mods) and the
latest mod versions and everything loaded!!!

Thanks for helping. We have a huge project in our club server and this was
a desperately needed mod.

Question....whats the limit of how many blocks can be moved at once?

**Comment by LolHens** [comment]
Nice! Yeah forge is still a little unstable for the 1.16.x versions as they are still changing stuff.
Currently there is no block limit but I will make that configurable in the future.

**Comment by MeijinViper** [comment]
Yeah, explains the new version daily, if not twice a day. Lol.

Question, is there a way to move blocks outside the rails? What we are
trying to do is move a platform along the ground. So like, have the rails
face up into the bottom of the platform and still move all of the platform
and the structure on it.

**Comment by LolHens** [comment]
Not yet. But I want to make a mod that can do this kind of stuff when I habe time for that.
