### ISSUE TITLE
Crash with geckolib (3.0 beta 7) ?

### ISSUE THREAD

**Issue by Artheow** [LolHens/mc-blockshifter#21]
Hi, i'm trying to build a modlist and i've found this https://pastebin.com/7V8jz6mp
I'm using Fabric with latest api, latest loader, 1.16.4 and the 1.3.2 version of blockshifter.

**Comment by LolHens** [comment]
@Artheow Could you provide a list of your mods folder?
I just installed the mentioned version of geckolib and blockshifter but could not reproduce the crash.

**Comment by Artheow** [comment]
My bad it's with the mod desolation and it's not compatible with latest geckolib yet
